import pandas as pd
import sys
import os

df = pd.read_csv('pitch2019.csv')
# print(df)
pitch_name = df['Name of your game pitch']
name = df['Your name']
slides = df['Link to your game pitch (preferably in google slides)']
NUM_PITCHES = len(name)
print(NUM_PITCHES)

PITCH_INFO_YAML_TEMPLATE = """  -
    name: {pitch_name}
    slides: {slides}
    members:
      - {name}
"""

VOTING_ROUND_YAML_TEMPLATE = """  -
    method: {method}
    votes: {votes}
    slots: {slots}
"""

VOTING_ROUNDS = [
    { 'method': 'rcv', 'votes': 3, 'slots': (NUM_PITCHES + 1) // 2 },
    { 'method': 'score', 'votes': 2, 'slots': 6 },
    { 'method': 'rcv', 'votes': 1, 'slots': 2 }
]

yaml = f"""# Note: this file was generated by {os.path.split(sys.argv[0])[1]}
pitches:
{''.join([
    PITCH_INFO_YAML_TEMPLATE.format(name=name, pitch_name=pitch_name, slides=slides)
    for name, pitch_name, slides in zip(name, pitch_name, slides)
])}

voting_rounds:
{''.join([
    VOTING_ROUND_YAML_TEMPLATE.format(**entry)
    for entry in VOTING_ROUNDS 
])}
"""

print(yaml)
with open('pitch2019.yaml', 'w') as f:
    f.write(yaml)
